# -*- coding: utf-8 -*-
"""Threat_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x7zmaQxoV_-a8ETLmb7ljZU0HYWuqaHa
"""

!pip install -q langchain
!pip install -q langchain-community
!pip install -q langchain-core
!pip install -q transformers
!pip install -q torch
!pip install -q accelerate
!pip install -q sentencepiece
!pip install -q pydantic

import re
import json
from transformers import pipeline

from transformers import pipeline

classifier = pipeline(
    "text-generation",
    model="distilgpt2",
    max_new_tokens=100
)

def detect_links(text):
    pattern = r'(https?://\S+|www\.\S+)'
    links = re.findall(pattern, text)

    return {
        "found": len(links) > 0,
        "links": links
    }

def detect_urgency(text):

    urgency_words = [
        "urgent",
        "immediately",
        "act now",
        "limited time",
        "expires",
        "last chance",
        "verify now",
        "update now"
    ]

    found = []

    for word in urgency_words:
        if word.lower() in text.lower():
            found.append(word)

    return found

def detect_scam_keywords(text):

    keywords = [
        "free",
        "winner",
        "lottery",
        "prize",
        "claim reward",
        "gift card",
        "bank account",
        "verify account",
        "click here",
        "password"
    ]

    found = []

    for keyword in keywords:
        if keyword.lower() in text.lower():
            found.append(keyword)

    return found

def llm_analysis(message):

    prompt = f"""
You are a cybersecurity expert.

Analyze the following message and explain:

1. Is it suspicious?
2. Is there phishing?
3. Is there urgency manipulation?
4. Is there a fake reward offer?
5. Give a short explanation.

Message:
{message}
"""

    result = classifier(prompt)

    return result[0]["generated_text"]

def threat_analysis_agent(message):

    links = detect_links(message)

    urgency = detect_urgency(message)

    scam_keywords = detect_scam_keywords(message)

    llm_result = llm_analysis(message)

    risk_score = 0

    if links["found"]:
        risk_score += 30

    risk_score += len(urgency) * 10

    risk_score += len(scam_keywords) * 10

    risk_score = min(risk_score, 100)

    if risk_score > 70:
        risk_level = "HIGH"

    elif risk_score > 40:
        risk_level = "MEDIUM"

    else:
        risk_level = "LOW"

    return {
        "risk_level": risk_level,
        "risk_score": risk_score,
        "links_detected": links["links"],
        "urgency_words": urgency,
        "suspicious_keywords": scam_keywords,
        "llm_explanation": llm_result
    }

sample_message = """
Congratulations!

You have won a $500 Amazon Gift Card.

Claim your reward immediately.

Click here:
https://fake-reward.com

Offer expires today.
"""

result = threat_analysis_agent(sample_message)

print(json.dumps(result, indent=4))